add button type for Dropdown and custom props for Modal custom footer
reportportal/ui-kit pull request #34
Opened 2024-08-14 10:01 UTC by Vadim73i

2024-08-15 10:31 UTC, maria-hambardzumian approved these changes

2024-08-15 10:38 UTC, AmsterGet requested changes

2024-08-15 10:38 UTC, AmsterGet commented on src/components/dropdown/dropdown.tsx
> +        type={'button'}
Let's replace with
```suggestion
        type="button"
```

2024-08-15 10:38 UTC, AmsterGet commented on src/components/modal/modal.tsx
> +                <CustomFooter closeHandler={closeModal} {...customFooterProps} />
Let's update to `createFooter` render prop. See the comment in service ui - https://github.com/reportportal/service-ui/pull/3964#discussion_r1718242684

2024-08-16 16:42 UTC, AmsterGet approved these changes

2024-08-16 16:43 UTC, merged